// MENU
'/menu/',
'/menu/index.html',
'/menu/app.js',

// BAB 1
'/menu/bab-1/',
'/menu/bab-1/index.html',
'/menu/bab-1/sub-bab/kasus-pelanggaran-hak-dan-kewajiban.html',
'/menu/bab-1/sub-bab/kasus-pelanggaran-hak-warga-negara.html',
'/menu/bab-1/sub-bab/kasus-pengingkaran-kewajiban.html',
'/menu/bab-1/sub-bab/makna-hak-dan-kewajiban-warga.html',
'/menu/bab-1/sub-bab/makna-hak-dan-kewajiban.html',
'/menu/bab-1/sub-bab/nilai-dasar-pancasila.html',
'/menu/bab-1/sub-bab/nilai-instrumental-pancasila.html',
'/menu/bab-1/sub-bab/nilai-praksis-pancasila.html',
'/menu/bab-1/sub-bab/penanganan-pelanggaran-hak-dan-kewajiban.html',
'/menu/bab-1/ulangan-akhir-bab/siap-ulangan.html',
'/menu/bab-1/ulangan-akhir-bab/pilihan-ganda/index.html',
'/menu/bab-1/ulangan-akhir-bab/essay/index.html',

// BAB 2
'/menu/bab-2/',
'/menu/bab-2/index.html',
'/menu/bab-2/sub-bab/dinamika-pelanggaran-hukum/kasus-pelanggaran-hukum.html',
'/menu/bab-2/sub-bab/dinamika-pelanggaran-hukum/partisipasi-dalam-perlindungan-dan-penegakkan-hukum.html',
'/menu/bab-2/sub-bab/dinamika-pelanggaran-hukum/sanksi-pelanggar-hukum.html',
'/menu/bab-2/sub-bab/hakikat-perlindungan/konsep-perlindungan.html',
'/menu/bab-2/sub-bab/hakikat-perlindungan/pentingnya-perlindungan.html',
'/menu/bab-2/sub-bab/peran-lembaga-penegak-hukum/peran-advokat.html',
'/menu/bab-2/sub-bab/peran-lembaga-penegak-hukum/peran-hakim.html',
'/menu/bab-2/sub-bab/peran-lembaga-penegak-hukum/peran-kejaksaan.html',
'/menu/bab-2/sub-bab/peran-lembaga-penegak-hukum/peran-kpk.html',
'/menu/bab-2/sub-bab/peran-lembaga-penegak-hukum/peran-polri.html',
'/menu/bab-2/ulangan-akhir-bab/siap-ulangan.html',
'/menu/bab-2/ulangan-akhir-bab/essay/index.html',
'/menu/bab-2/ulangan-akhir-bab/pilihan-ganda',

// GAMBAR DAN FILE LAINNYA
'/images/arrow-left-white.png',
'/images/arrow-left.png',
'/images/author.png',
'/images/bendera.png',
'/images/chevron-right-black.png',
'/images/chevron-right.png',
'/images/daftar-isi.png',
'/images/device.gif',
'/images/download.png',
'/images/exam.png',
'/images/garuda.png',
'/images/gcr.png',
'/images/home.png',
'/images/logo-smk.png',
'/images/ilustrasi.png',
'/images/logo.png',
'/images/materi.png',
'/images/menu.png',
'/images/next.png',
'/images/pkn.png',
'/images/prev.png',
'/images/sign-in.png',
'/images/user-grup.png',
'/images/user.png',
'/images/src/anak-putus-sekolah.jpg',
'/images/src/bentrokan.jpg',
'/images/src/demo-buruh-pmpb-menuju-istana-negara-566.jpg',
'/images/src/gotong-royong.jpg',
'/images/src/hak-kewajiban.jpg',
'/images/src/hak-pendidikan.jpg',
'/images/src/kasus-pelanggaran-hak.png',
'/images/src/melanggar-lalu-lintas.jpg',
'/images/src/nilai-praksis-pancasila-1.jpg',
'/images/src/nilai-praksis-pancasila.jpg',
'/images/src/partisipasi-masyarakat.jpg',
'/images/src/penyalahgunaan-teknologi.jpg',
'/images/src/praktik-perlindungan-hukum.jpg',
'/images/src/rapat-dengar-pendapat.jpg',
'/images/src/rumah-kumuh.jpg',
'/images/src/sikap-tidak-toleran.jpg',
'/images/src/tabel-2.1.jpg',
'/images/src/tugas-mandiri-1-1.jpg',
'/images/src/tugas-mandiri-2.1.png',

// FILE DOWNLOAD
// '/download/Buku PPKN Kelas XII.pdf',